swagger: 2.0
info:
    title: "Sample API"
    description: "API description in Markdown."
    version: "1.0.0"

host: "127.0.0.1:8000"
basePath: "/v1"
schemes:
  - https

paths:
  flights:
    get:
      summary: "Returns a list of users."
      description: "Optional extended description in Markdown."
      produces:
        - application/json
      responses:
        "200":
          description: OK